image: php:latest

stages:
  - test
cache:
  paths:
    - vendor/

before_script:
  - composer install

test:
  stage: test
  script:
    - vendor/bin/phpunit
  only:
    - branches
  except:
    - master

.pre-merge:
  stage: test
  script:
    - echo "Merge request event detected. Running tests..."
    - vendor/bin/phpunit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request"'